### ISSUE TITLE
False Positive: Brain Jacker

### ISSUE THREAD

**Issue by Gabriel-T-Harris** [more-lost-arts/more-lost-arts.github.io#1]
**Permalink:** https://more-lost-arts.github.io/#6263_1

A lot of them are exaggerating differences due to art off centerness.

**Comment by gallantron** [comment]
Brain Jacker actually _does_ have a difference, the artwork shift just threw the detection algorithm off. I've gone and manually fixed the heatmap -- thanks for your report!

So far, artworks that shift slightly seem to indicate that _something_ has also changed about the artwork, though the algorithm might not necessarily find the correct spot.
